"""
Django settings for bloomwebstoreforamvera project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-10f)1l+i0!rr!5r!_gcwrux+x$)27q$%5fl0f^jnb6h3egw5wt'
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'bwstore-battatotal.amvera.io'] #'.amvera.io']

CSRF_TRUSTED_ORIGINS = [
    'https://bwstore-battatotal.amvera.io'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop.apps.ShopConfig',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bloomwebstoreforamvera.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'bloomwebstoreforamvera.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Проверка, запущены ли мы на Amvera (перенес снизу от медиа)
IS_AMVERA = os.getenv('AMVERA') or os.getenv('AMVERA_APP_ID')

# для Amvera
if IS_AMVERA:
    # Путь к БД в постоянном хранилище Amvera
    DB_PATH = '/data/db.sqlite3'
else:
    # Локальный путь
    DB_PATH = BASE_DIR / 'db.sqlite3'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DB_PATH,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # Папка, куда соберутся файлы

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Проверка, запущены ли мы на Amvera
IS_AMVERA = os.getenv('AMVERA') or os.getenv('AMVERA_APP_ID')

# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Настройки медиа
MEDIA_URL = '/media/'

if IS_AMVERA:
    # В облаке Amvera файлы сохраняем только в /data
    MEDIA_ROOT = '/data/media'
else:
    # Локально — в обычную папку проекта
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


CART_SESSION_ID = 'cart'


# --- Настройки безопасности сессий ---

# 1. Защита от XSS-атак. Делает куки недоступными для JavaScript.
# Это стандарт безопасности для защиты сессии анонимного пользователя.
SESSION_COOKIE_HTTPONLY = True

# 2. Защита от CSRF-атак. Браузер не будет отправлять куки при
# переходах со сторонних подозрительных сайтов.
SESSION_COOKIE_SAMESITE = 'Lax'

# 3. Принцип минимизации хранения данных.
# Куки (и корзина) удалятся сразу, как только пользователь закроет вкладку.
# Это избавляет от необходимости хранить "хвосты" данных в БД годами.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 4. сайт работает через HTTPS,
# включина передача куки только по зашифрованному каналу.
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# 5. Возраст сессии (на случай, если браузер не закрыли).
# Ограничен 24 часами (в секундах).
SESSION_COOKIE_AGE = 86400