# Generated by Django 5.1.5 on 2025-05-12 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=200)),
                ('imageMain', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Основное изображение')),
                ('image1', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение 1')),
                ('image2', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение 3')),
                ('image4', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение 4')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('materials', models.TextField(blank=True, verbose_name='Материалы')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('size', models.CharField(max_length=200, verbose_name='Размер')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('quantity', models.IntegerField(verbose_name='Количество в наличии')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категории товаров')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['id', 'slug'], name='shop_produc_id_f21274_idx')],
            },
        ),
    ]
