# Generated by Django 5.1.5 on 2025-07-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='Отменен'),
        ),
        migrations.AddField(
            model_name='order',
            name='waiting_for_capture',
            field=models.BooleanField(default=False, verbose_name='Ожидает подтверждения оплаты администратором'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен (Одобрен администратором и успешен)'),
        ),
    ]
